<?php
namespace Modules\Guesthouse\Controllers;

use Modules\Booking\Models\Enquiry;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Guesthouse\Models\Guesthouse;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Booking\Models\Booking;
use Modules\Guesthouse\Models\GuesthouseTerm;
use Modules\Guesthouse\Models\GuesthouseTranslation;

class VendorController extends FrontendController
{
    protected $guesthouseClass;
    protected $guesthouseTranslationClass;
    protected $guesthouseTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;

    public function __construct()
    {
        parent::__construct();
        $this->guesthouseClass = Guesthouse::class;
        $this->guesthouseTranslationClass = GuesthouseTranslation::class;
        $this->guesthouseTermClass = GuesthouseTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->bookingClass = Booking::class;
    }

    public function callAction($method, $parameters)
    {
        if(!Guesthouse::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('guesthouse_view');
        $user_id = Auth::id();
        $list_guesthouse = $this->guesthouseClass::where("create_user", $user_id)->orderBy('id', 'asc');
        $data = [
            'rows' => $list_guesthouse->paginate(1),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Guesthouses'),
                    'url'  => route('guesthouse.vendor.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Manage Guesthouses"),
        ];
        return view('Guesthouse::frontend.vendorGuesthouse.index', $data);
    }

    public function create(Request $request)
    {
        $this->checkPermission('guesthouse_create');
        $row = new $this->guesthouseClass();
        $data = [
            'row'           => $row,
            'translation' => new $this->guesthouseTranslationClass(),
            'guesthouse_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'guesthouse')->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Guesthouses'),
                    'url'  => route('guesthouse.vendor.index')
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Create Guesthouses"),
        ];
        return view('Guesthouse::frontend.vendorGuesthouse.detail', $data);
    }


    public function store( Request $request, $id ){

        if($id>0){
            $this->checkPermission('guesthouse_update');
            $row = $this->guesthouseClass::find($id);
            if (empty($row)) {
                return redirect(route('guesthouse.vendor.index'));
            }

            if($row->create_user != Auth::id() and !$this->hasPermission('guesthouse_manage_others'))
            {
                return redirect(route('guesthouse.vendor.index'));
            }
        }else{
            $this->checkPermission('guesthouse_create');
            $row = new $this->guesthouseClass();
            $row->status = "publish";
            if(setting_item("guesthouse_vendor_create_service_must_approved_by_admin", 0)){
                $row->status = "pending";
            }
        }
        $dataKeys = [
            'title',
            'content',
            'slug',
            'video',
            'image_id',
            'banner_image_id',
            'gallery',
            'is_featured',
            'policy',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'star_rate',
            'price',
            'sale_price',
            'check_in_time',
            'check_out_time',
            'allow_full_day',
            'enable_extra_price',
            'extra_price',
        ];
        if($this->hasPermission('guesthouse_manage_others')){
            $dataKeys[] = 'create_user';
        }

        $row->fillByAttr($dataKeys,$request->input());
	    $row->ical_import_url  = $request->ical_import_url;

        $res = $row->saveOriginOrTranslation($request->input('lang'),true);

        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }

            if($id > 0 ){
                return back()->with('success',  __('Guesthouse updated') );
            }else{
                return redirect(route('guesthouse.vendor.edit',['id'=>$row->id]))->with('success', __('Guesthouse created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->guesthouseTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->guesthouseTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->guesthouseTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function edit(Request $request, $id)
    {
        $this->checkPermission('guesthouse_update');
        $user_id = Auth::id();
        $row = $this->guesthouseClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('guesthouse.vendor.index'))->with('warning', __('Space not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'           => $row,
            'guesthouse_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'guesthouse')->get(),
            "selected_terms" => $row->terms->pluck('term_id'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Guesthouses'),
                    'url'  => route('guesthouse.vendor.index')
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Edit Guesthouses"),
        ];
        return view('Guesthouse::frontend.vendorGuesthouse.detail', $data);
    }

    public function delete($id)
    {
        $this->checkPermission('guesthouse_delete');
        $user_id = Auth::id();
        $query = $this->guesthouseClass::where("create_user", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->delete();
        }
        return redirect(route('guesthouse.vendor.index'))->with('success', __('Delete guesthouse success!'));
    }

    public function bulkEditGuesthouse($id , Request $request){
        $this->checkPermission('guesthouse_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->guesthouseClass::where("create_user", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if(empty($query)){
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action){
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                break;
        }
        $query->save();
        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReport(Request $request)
    {
        $data = [
            'bookings' => $this->bookingClass::getBookingHistory($request->input('status'), false , Auth::id() , 'guesthouse'),
            'statues'  => config('booking.statuses'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Guesthouse'),
                    'url'  => route('guesthouse.vendor.index')
                ],
                [
                    'name' => __('Booking Report'),
                    'class'  => 'active'
                ]
            ],
            'page_title'         => __("Booking Report"),
        ];
        return view('Guesthouse::frontend.vendorGuesthouse.bookingReport', $data);
    }

    public function bookingReportBulkEdit($booking_id , Request $request){
        $status = $request->input('status');
        if (!empty(setting_item("guesthouse_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if(!empty($item)){
                $item->status = $status;
                $item->save();
                $item->sendStatusUpdatedEmails();
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }
}
